-- Migration: Dynamic Spiritual Calendar and General Scheduled Notification System
-- Created on: 2026-06-11

-- 1. Create Spiritual Calendar Table
CREATE TABLE IF NOT EXISTS public.spiritual_calendar (
    date_key DATE PRIMARY KEY, -- '2026-06-11' etc.
    title TEXT NOT NULL,
    date_str TEXT NOT NULL,
    deity TEXT,
    deity_label TEXT,
    vrat_type TEXT,
    importance TEXT CHECK (importance IN ('high', 'medium', 'normal')),
    one_liner TEXT,
    description TEXT,
    why_observe JSONB,
    benefits JSONB,
    how_to_perform JSONB,
    food_guidelines JSONB,
    mantras_prayers JSONB,
    vrat_katha TEXT,
    puja_timings JSONB,
    recommended_puja JSONB,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.spiritual_calendar ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
DROP POLICY IF EXISTS "Allow public read access" ON public.spiritual_calendar;
CREATE POLICY "Allow public read access" ON public.spiritual_calendar FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow auth all access" ON public.spiritual_calendar;
CREATE POLICY "Allow auth all access" ON public.spiritual_calendar FOR ALL USING (true) WITH CHECK (true);

-- 4. Register Trigger for updated_at tracking
DROP TRIGGER IF EXISTS set_timestamp_spiritual_calendar ON public.spiritual_calendar;
CREATE TRIGGER set_timestamp_spiritual_calendar BEFORE UPDATE ON public.spiritual_calendar
  FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

-- 5. Add Table to Supabase Realtime Publication
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'spiritual_calendar'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.spiritual_calendar;
  END IF;
END
$$;

-- 6. Insert 20 Seed Calendar Entries
INSERT INTO public.spiritual_calendar (
    date_key, title, date_str, deity, deity_label, vrat_type, importance, one_liner, description,
    why_observe, benefits, how_to_perform, food_guidelines, mantras_prayers, vrat_katha, puja_timings, recommended_puja
) VALUES
(
    '2026-06-11',
    'Yogini Ekadashi Vrat',
    'June 11, 2026',
    'Lord Vishnu 📿',
    'vishnu',
    'Ekadashi',
    'high',
    'Sacred fast to wash away major past misdeeds and purify the soul.',
    'Observed on Krishna Paksha of Ashadha month. Helps attain high self-control.',
    '["To purify the soul from past negative karmas", "Seek ultimate blessings of Lord Vishnu", "Cleanse internal digestive systems"]'::jsonb,
    '["Deep mental peace", "Elimination of past misdeeds", "Harmony in family", "Prosperity in business", "Physical rejuvenation"]'::jsonb,
    '["Wake up in Brahma Muhurt and bathe", "Light a pure cow ghee lamp", "Offer yellow flowers and Tulsi leaves", "Read Yogini Ekadashi Vrat Katha", "Chant Vishnu Sahasranama", "Perform Parana next morning"]'::jsonb,
    '{"allowed": ["Fruits", "Milk", "Singhara flour", "Sabudana", "Potatoes"], "prohibited": ["Rice", "Wheat", "Lentils", "Onion", "Garlic"]}'::jsonb,
    '[{"name": "Vishnu Mantra", "mantra": "Om Namo Bhagavate Vasudevaya", "count": "108 times"}]'::jsonb,
    'A king named Kuber was a devout worshiper of Lord Shiva. His gardener, Hemamali, forgot to gather flowers because he was spending time with his beautiful wife. Kuber cursed Hemamali to suffer from leprosy and be banished. Hemamali wandered in the forest until he met Sage Markandeya, who advised him to observe Yogini Ekadashi fast. Hemamali fasted devoutly, cured his leprosy, and returned to his wife in divine health.',
    '[{"label": "Shubh Muhurat", "value": "07:15 AM - 09:30 AM"}, {"label": "Parana Time", "value": "06:15 AM - 08:30 AM (June 12)"}]'::jsonb,
    '{"name": "Maha Vishnu Puja", "price": "₹1,500", "duration": "45 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-12',
    'Ashadha Pradosh Vrat',
    'June 12, 2026',
    'Lord Shiva 🔱',
    'shiva',
    'Pradosh',
    'medium',
    'Auspicious twilight fast for health, long life, and mental peace.',
    'Trayodashi tithi of Krishna Paksha. Shiva descends to remove sorrow during twilight.',
    '["Seek Shiva''s blessings", "Purify karma", "Restore health"]'::jsonb,
    '["Mental peace", "Karmic clearance", "Long life", "Aura purification"]'::jsonb,
    '["Wake up early", "Light lamp", "twilight prayers", "Offer milk/honey on Shivling", "Aarti"]'::jsonb,
    '{"allowed": ["Fruits", "Milk", "Rock salt"], "prohibited": ["Onion", "Garlic", "Grains"]}'::jsonb,
    '[{"name": "Shiva Mantra", "mantra": "Om Namah Shivaya", "count": "108 times"}]'::jsonb,
    'Observed to obtain Shiva''s special twilight blessings and clear life obstacles.',
    '[{"label": "Pradosh Kaal", "value": "06:45 PM - 08:15 PM"}]'::jsonb,
    '{"name": "Rudrabhishek Puja", "price": "₹2,100", "duration": "60 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-13',
    'Shani Trayodashi Special',
    'June 13, 2026',
    'Lord Hanuman / Shani Dev 🛡️',
    'hanuman',
    'Weekly',
    'normal',
    'Powerful day to neutralize Saturn (Shani) doshas and win over obstacles.',
    'Saturday Trayodashi alignment. Praying to Lord Hanuman wards off evil planetary transits.',
    '["Mitigate Sade Sati", "Build patience", "Courage"]'::jsonb,
    '["Reduce Saturn restrictions", "Confidence boost", "Protection from evil eyes"]'::jsonb,
    '["Light mustard oil lamp", "Chant Hanuman Chalisa", "Donate black items"]'::jsonb,
    '{"allowed": ["Vegetarian foods", "Sweets"], "prohibited": ["Alcohol", "Non-veg"]}'::jsonb,
    '[{"name": "Shani Mantra", "mantra": "Om Sham Shanicharaya Namah", "count": "108 times"}]'::jsonb,
    'Lord Hanuman protected Saturn from Ravana, making Hanuman worship best for pacifying Shani.',
    '[{"label": "Shubh Shani Muhurat", "value": "06:00 AM - 08:00 AM"}]'::jsonb,
    '{"name": "Hanuman Shanti Puja", "price": "₹1,200", "duration": "45 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-14',
    'Sunday Surya Dev Puja',
    'June 14, 2026',
    'Surya Dev ☀️',
    'surya',
    'Weekly',
    'normal',
    'Sunday fast for physical vitality, confidence, and leadership.',
    'Sunday is ruled by the Sun. Offer Arghya to rise above obstacles.',
    '["Strength", "Success", "Good vision"]'::jsonb,
    '["Clear skin", "Aura glow", "Self-confidence", "Administrative success"]'::jsonb,
    '["Offer Arghya to rising sun", "Recite Aditya Hridaya Stotram", "Saltless fasting"]'::jsonb,
    '{"allowed": ["Wheat sweet meals", "Fruits"], "prohibited": ["Salt", "Oil", "Onion"]}'::jsonb,
    '[{"name": "Surya Mantra", "mantra": "Om Ghrini Suryaya Namah", "count": "108 times"}]'::jsonb,
    'Aditya Hridaya Stotram recited by Lord Rama for victory.',
    '[{"label": "Sunrise Arghya", "value": "05:32 AM - 06:15 AM"}]'::jsonb,
    '{"name": "Surya Shanti Puja", "price": "₹1,500", "duration": "45 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-15',
    'Somvati Amavasya',
    'June 15, 2026',
    'Lord Shiva / Ancestors 🔱',
    'shiva',
    'Weekly',
    'high',
    'A highly auspicious Monday Amavasya for ancestral peace and Shiva''s grace.',
    'Fasting on this day brings peace, cleanses genetic lineage blocks, and brings family peace.',
    '["Ancestors peace", "Clear lineage blockages", "Shiva blessings"]'::jsonb,
    '["Household peace", "Lineage blessings", "Karma clearance"]'::jsonb,
    '["Take bath in holy river or with Ganga water", "Perform Pitru Tarpan", "Pradakshina of Peepal tree"]'::jsonb,
    '{"allowed": ["Fruits", "Milk", "Khichdi post Tarpan"], "prohibited": ["Onion", "Garlic", "Spices"]}'::jsonb,
    '[{"name": "Pitru Mantra", "mantra": "Om Pitru Devataye Namah", "count": "108 times"}]'::jsonb,
    'Worshiping ancestors on Monday Amavasya frees them from suffering.',
    '[{"label": "Tarpan Muhurat", "value": "09:00 AM - 12:00 PM"}]'::jsonb,
    '{"name": "Pitru Tarpan Puja", "price": "₹2,500", "duration": "60 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-16',
    'Ashadha Gupta Navratri Begins',
    'June 16, 2026',
    'Goddess Durga 🦁',
    'durga',
    'Navratri',
    'high',
    'Nine nights of deep sadhana and fasting invoking Goddess Durga''s protective powers.',
    'Ashadha Gupta Navratri is observed for spiritual empowerment and inner transformation.',
    '["Shakti invocation", "Self protection", "Mental strength"]'::jsonb,
    '["Inner strength", "Removal of fears", "Spiritual advancement"]'::jsonb,
    '["Ghatasthapana", "Light Akhand Jyoti", "Durga Chalisa chanting"]'::jsonb,
    '{"allowed": ["Kuttu flour", "Singhara flour", "Fruits"], "prohibited": ["Wheat", "Rice", "Table salt"]}'::jsonb,
    '[{"name": "Durga Mantra", "mantra": "Om Dum Durgayei Namaha", "count": "108 times"}]'::jsonb,
    'Nine forms of Durga are worshiped in secret for highest yogic power.',
    '[{"label": "Ghatasthapana", "value": "06:18 AM - 08:30 AM"}]'::jsonb,
    '{"name": "Maha Durga Puja", "price": "₹3,100", "duration": "90 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-17',
    'Chandra Darshan',
    'June 17, 2026',
    'Chandra Dev 🌙',
    'shiva',
    'Weekly',
    'normal',
    'Evening moon sighting to balance emotions and calm mental stress.',
    'Sighting the crescent moon after Amavasya brings sensory peace.',
    '["Calm mind", "Balance emotions", "Health"]'::jsonb,
    '["Reduced stress", "Improved sleep", "Sensory clarity"]'::jsonb,
    '["Sight moon in evening", "Offer water (Arghya) to moon", "Chant Chandra mantra"]'::jsonb,
    '{"allowed": ["Vegetarian satvik food"], "prohibited": ["Sour foods", "Heavy grains"]}'::jsonb,
    '[{"name": "Chandra Mantra", "mantra": "Om Som Somaya Namah", "count": "108 times"}]'::jsonb,
    'Worship of Chandra Dev restores beauty and peace of mind.',
    '[{"label": "Moonrise sighting", "value": "07:30 PM - 08:30 PM"}]'::jsonb,
    '{"name": "Chandra Grah Shanti Puja", "price": "₹1,500", "duration": "45 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-18',
    'Varada Vinayaka Chaturthi',
    'June 18, 2026',
    'Lord Ganesha 🐘',
    'ganesha',
    'Chaturthi',
    'medium',
    'Fasting day to seek Ganesha''s blessings for resolving career and study hurdles.',
    'Vinayaka Chaturthi of Ashadha month. Offer Durva grass and modaks.',
    '["Intellect", "Obstacle clearance", "Success"]'::jsonb,
    '["Clear thoughts", "Success in jobs/exams", "Business growth"]'::jsonb,
    '["Abhishek of Ganesha", "Offer 21 Durva grass blades", "Offer Modak sweets"]'::jsonb,
    '{"allowed": ["Sabudana", "Fruits", "Milk"], "prohibited": ["Salt", "Grains"]}'::jsonb,
    '[{"name": "Ganesha Mantra", "mantra": "Om Gan Ganapataye Namah", "count": "108 times"}]'::jsonb,
    'Observed to obtain Ganesha''s divine blessing for starting new works.',
    '[{"label": "Madhyahna Ganesha Puja", "value": "11:00 AM - 01:30 PM"}]'::jsonb,
    '{"name": "Ganesha Vignaharta Puja", "price": "₹1,200", "duration": "45 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-19',
    'Skanda Sashti Vrat',
    'June 19, 2026',
    'Lord Kartikeya 🛡️',
    'hanuman',
    'Weekly',
    'normal',
    'Fasting dedicated to Lord Kartikeya for victory over internal and external enemies.',
    'Observed on Sashti tithi. Builds courage and protects family.',
    '["Victory", "Courage", "Children well-being"]'::jsonb,
    '["Removes fear", "Victory in conflicts", "Family protection"]'::jsonb,
    '["Worship Lord Kartikeya", "Offer red flowers", "Light lamps"]'::jsonb,
    '{"allowed": ["Fruits", "Milk", "Nuts"], "prohibited": ["Grains", "Salt"]}'::jsonb,
    '[{"name": "Kartikeya Mantra", "mantra": "Om Saravana Bhava", "count": "108 times"}]'::jsonb,
    'Kartikeya defeated demon Surapadman on Sashti tithi.',
    '[{"label": "Puja Muhurat", "value": "09:00 AM - 11:30 AM"}]'::jsonb,
    '{"name": "Kartikeya Shakti Puja", "price": "₹1,800", "duration": "50 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-20',
    'Mithuna Sankranti',
    'June 20, 2026',
    'Surya Dev ☀️',
    'surya',
    'Weekly',
    'normal',
    'Solar transit marking the sun entering Gemini. Excellent day for charity.',
    'Worshiping Surya Dev and donating copper or wheat brings good karma.',
    '["Charity benefits", "Solar blessings", "Good health"]'::jsonb,
    '["Good health", "Wealth through charity", "Career success"]'::jsonb,
    '["Snan before sunrise", "Donate copper vessels, grains", "Surya Puja"]'::jsonb,
    '{"allowed": ["Satvik foods", "Milk"], "prohibited": ["Non-veg", "Alcohol"]}'::jsonb,
    '[{"name": "Surya Mantra", "mantra": "Om Ghrini Suryaya Namah", "count": "108 times"}]'::jsonb,
    'Transitions of Sun represent change of seasons and auspicious donor phases.',
    '[{"label": "Transit Muhurat", "value": "08:00 AM - 11:00 AM"}]'::jsonb,
    '{"name": "Maha Surya Puja", "price": "₹1,500", "duration": "45 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-21',
    'Bhanu Saptami',
    'June 21, 2026',
    'Surya Dev ☀️',
    'surya',
    'Weekly',
    'medium',
    'Rare Sunday Saptami alignment to cure long-standing health issues.',
    'Reciting Aditya Hridaya Stotram and fasting brings massive vitality.',
    '["Cure ailments", "Vitality", "Self respect"]'::jsonb,
    '["Overcomes bone/eye issues", "Success in jobs", "Patience"]'::jsonb,
    '["Arghya with copper lota", "Recite Surya Dev 108 names", "Saltless diet"]'::jsonb,
    '{"allowed": ["Sweet wheat roti", "Fruits"], "prohibited": ["Salt", "Spices"]}'::jsonb,
    '[{"name": "Surya Ashtakam", "mantra": "Om Namah Suryaya", "count": "108 times"}]'::jsonb,
    'Sunday Saptami is equivalent to Surya Jayanti, highly dynamic.',
    '[{"label": "Auspicious Sunrise", "value": "05:33 AM - 06:30 AM"}]'::jsonb,
    '{"name": "Maha Surya Puja", "price": "₹1,800", "duration": "50 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-22',
    'Masik Durgashtami',
    'June 22, 2026',
    'Goddess Durga 🦁',
    'durga',
    'Navratri',
    'medium',
    'Monthly fast invoking Goddess Durga for victory over negative forces.',
    'Observed on Shukla Paksha Ashtami. Light a deep ghee lamp.',
    '["Victory", "Household safety", "Destroy ego"]'::jsonb,
    '["Destroys negative thoughts", "Protection from obstacles", "Marital peace"]'::jsonb,
    '["Abhishek of Durga", "Chant Argala Stotram", "Offer red flowers"]'::jsonb,
    '{"allowed": ["Satvik foods", "Fruits", "Milk"], "prohibited": ["Grains", "Salt"]}'::jsonb,
    '[{"name": "Navarna Mantra", "mantra": "Om Aing Hreeng Kleeng Chamundaye Viche", "count": "108 times"}]'::jsonb,
    'Goddess Durga appeared on Ashtami to annihilate powerful demons.',
    '[{"label": "Ashtami Muhurat", "value": "08:30 AM - 11:30 AM"}]'::jsonb,
    '{"name": "Navgrah Durga Puja", "price": "₹2,200", "duration": "60 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-23',
    'Bhadli Navami',
    'June 23, 2026',
    'Lord Vishnu 📿',
    'vishnu',
    'Weekly',
    'normal',
    'Highly auspicious day for marriage preparations and invoking Vishnu.',
    'The final auspicious day before Devshayani Ekadashi start of Chaturmas.',
    '["Inauguration of works", "Prosperity", "Vishnu blessing"]'::jsonb,
    '["Success in future works", "Stable finances", "Good matches"]'::jsonb,
    '["Worship Vishnu-Laxmi", "Offer dry fruit prasad", "Chant Vishnu prayers"]'::jsonb,
    '{"allowed": ["Vegetarian meals"], "prohibited": ["Non-veg", "Garlic"]}'::jsonb,
    '[{"name": "Laxmi Vishnu Mantra", "mantra": "Om Laxmi Narayanaye Namah", "count": "108 times"}]'::jsonb,
    'Observed to thank Lord Vishnu before he enters Chaturmas sleep.',
    '[{"label": "Shubh Muhurat", "value": "09:00 AM - 12:00 PM"}]'::jsonb,
    '{"name": "Maha Vishnu Archana", "price": "₹1,500", "duration": "45 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-24',
    'Asha Dashami Vrat',
    'June 24, 2026',
    'Goddess Parvati 🌸',
    'lakshmi',
    'Weekly',
    'normal',
    'Devotional fast observed to manifest wishes and build marital harmony.',
    'Devotees worship Goddess Parvati for a peaceful and prosperous married life.',
    '["Marriage blessings", "Wish manifestation", "Aura cleaning"]'::jsonb,
    '["Marital peace", "Fulfillment of positive aspirations", "Stress relief"]'::jsonb,
    '["Worship Shiva-Parvati", "Light incense", "Chant Parvati mantras"]'::jsonb,
    '{"allowed": ["Fruits", "Milk", "Sabudana"], "prohibited": ["Onions", "Garlic", "Grains"]}'::jsonb,
    '[{"name": "Parvati Mantra", "mantra": "Om Umayei Namaha", "count": "108 times"}]'::jsonb,
    'Observed by queens and ladies in ancient times to bring peace to kingdoms.',
    '[{"label": "Morning Puja", "value": "07:30 AM - 09:30 AM"}]'::jsonb,
    '{"name": "Shiv Parvati Vivah Puja", "price": "₹2,500", "duration": "60 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-25',
    'Devshayani Ekadashi Vrat',
    'June 25, 2026',
    'Lord Vishnu 📿',
    'vishnu',
    'Ekadashi',
    'high',
    'Commencement of Chaturmas; Lord Vishnu enters cosmic sleep for four months.',
    'Shukla Paksha Ekadashi of Ashadha. Fasting brings high spiritual alignment.',
    '["Chaturmas start", "Punya accumulation", "Health detox"]'::jsonb,
    '["Spiritual elevation", "Digestive reset", "Family wellness"]'::jsonb,
    '["Wake up in Brahma Muhurta", "Strict fast", "Keep night vigil"]'::jsonb,
    '{"allowed": ["Fruits", "Milk", "No water (optional)"], "prohibited": ["Wheat", "Rice", "Lentils"]}'::jsonb,
    '[{"name": "Vishnu Mantra", "mantra": "Om Namo Bhagavate Vasudevaya", "count": "108 times"}]'::jsonb,
    'Lord Vishnu goes to Patala Loka to rest on Shesha Naga for Chaturmas.',
    '[{"label": "Puja Shubh Kaal", "value": "06:30 AM - 08:30 AM"}]'::jsonb,
    '{"name": "Satyanarayan Vrat Katha Puja", "price": "₹2,500", "duration": "75 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-26',
    'Ashadha Shukla Pradosh Vrat',
    'June 26, 2026',
    'Lord Shiva 🔱',
    'shiva',
    'Pradosh',
    'medium',
    'Auspicious evening fast to remove debts and clean negative energies.',
    'Trayodashi tithi of Shukla Paksha. Worship Shiva in Pradosh Kaal.',
    '["Debt removal", "Health protection", "Spiritual peace"]'::jsonb,
    '["Clear financial blocks", "Anxiety relief", "Better focus"]'::jsonb,
    '["Fast during day", "Shiva Abhishek in evening", "Light ghee lamp"]'::jsonb,
    '{"allowed": ["Sendha salt items", "Milk", "Fruits"], "prohibited": ["Wheat", "Onion", "Garlic"]}'::jsonb,
    '[{"name": "Shiva Mantra", "mantra": "Om Namah Shivaya", "count": "108 times"}]'::jsonb,
    'Observing Shukla Pradosh brings wealth and long healthy life.',
    '[{"label": "Pradosh twilight", "value": "06:46 PM - 08:16 PM"}]'::jsonb,
    '{"name": "Rudrabhishek Puja", "price": "₹3,500", "duration": "90 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-27',
    'Jaya Parvati Vrat Begins',
    'June 27, 2026',
    'Goddess Parvati 🌸',
    'lakshmi',
    'Weekly',
    'normal',
    'Five-day fast observed by women for family well-being and health.',
    'Dedicated to Shiva-Parvati. Commences on Ashadha Shukla Trayodashi.',
    '["Husband long life", "Household prosperity", "Virtuous children"]'::jsonb,
    '["Domestic happiness", "Spiritual dedication", "Peace of mind"]'::jsonb,
    '["Worship Parvati idol", "Grow small wheat seeds", "Avoid salted foods"]'::jsonb,
    '{"allowed": ["Unsalted foods", "Fruits", "Milk"], "prohibited": ["Salt", "Grains (partial)"]}'::jsonb,
    '[{"name": "Parvati Aarti", "mantra": "Om Jai Ambe Gauri", "count": "1 time"}]'::jsonb,
    'Observed to obtain Jaya and Parvati blessings for lineage stability.',
    '[{"label": "Sthapana Muhurat", "value": "08:00 AM - 10:00 AM"}]'::jsonb,
    '{"name": "Shiv Parvati Vivah Puja", "price": "₹2,500", "duration": "60 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-28',
    'Kokila Vrat',
    'June 28, 2026',
    'Goddess Sati / Parvati 🌸',
    'lakshmi',
    'Weekly',
    'normal',
    'Worshiping Goddess Parvati in the form of a Kokila (cuckoo) for harmony.',
    'Observed on Ashadha Purnima. Brings relationship peace and resolves delays.',
    '["Find good partner", "Restore broken relations", "Remove delays"]'::jsonb,
    '["Attracts caring partner", "Resolves communication gaps", "Self-confidence"]'::jsonb,
    '["Worship clay cuckoo bird", "Offer red flowers", "Fast until evening"]'::jsonb,
    '{"allowed": ["Fruits", "Milk", "Satvik meals"], "prohibited": ["Non-satvik foods", "Salt"]}'::jsonb,
    '[{"name": "Devi Stotra", "mantra": "Om Dum Durgayei Namaha", "count": "108 times"}]'::jsonb,
    'Goddess Sati was cursed to live as a cuckoo for 1000 years, during which she worshipped Shiva.',
    '[{"label": "Kokila Puja Muhurat", "value": "07:00 AM - 09:00 AM"}]'::jsonb,
    '{"name": "Navgrah Durga Puja", "price": "₹2,200", "duration": "60 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-29',
    'Guru Purnima',
    'June 29, 2026',
    'Lord Shiva / Guru Dev 🔱',
    'shiva',
    'Weekly',
    'high',
    'A sacred day to honor spiritual mentors, teachers, and lineage gurus.',
    'Celebrated on Ashadha Purnima. Recite Guru Gita and perform puja.',
    '["Honor spiritual gurus", "Acquire wisdom", "Express gratitude"]'::jsonb,
    '["Intellectual wisdom", "Clear direction in life", "Inner satisfaction"]'::jsonb,
    '["Perform Guru Paduka Puja", "Chant Guru Gita", "Offer fruits and donation to Guru"]'::jsonb,
    '{"allowed": ["Satvik vegetarian meals", "Sweets"], "prohibited": ["Onion", "Garlic", "Heavy non-satvik foods"]}'::jsonb,
    '[{"name": "Guru Mantra", "mantra": "Guru Brahma Guru Vishnu Guru Devo Maheshwarah...", "count": "108 times"}]'::jsonb,
    'Birth anniversary of Sage Veda Vyasa, compiler of 4 Vedas and Puranas.',
    '[{"label": "Guru Paduka Puja", "value": "09:00 AM - 11:30 AM"}]'::jsonb,
    '{"name": "Maha Shiva Puja & Abhishek", "price": "₹2,100", "duration": "50 mins", "route": "/all_pujas"}'::jsonb
),
(
    '2026-06-30',
    'Sawan Somvar Begins',
    'June 30, 2026',
    'Lord Shiva 🔱',
    'shiva',
    'Weekly',
    'high',
    'The highly sacred Sawan Monday fasts for ultimate health, prosperity, and peace.',
    'The start of holy Shravan month Somvar Vrats. Perform Shiva Jal Abhishek.',
    '["Shiva devotion", "Eradicate illness", "Family protection"]'::jsonb,
    '["Ultimate physical health", "Domestic prosperity", "Clear bad transits"]'::jsonb,
    '["Abhishek of Shivling with Ganga water and milk", "Offer Bilva leaves", "Chant Solah Somvar Katha"]'::jsonb,
    '{"allowed": ["Fruits", "Milk", "Singhara flour", "Sendha salt"], "prohibited": ["Wheat", "Rice", "Normal table salt"]}'::jsonb,
    '[{"name": "Shiva Mahamrityunjaya", "mantra": "Om Tryambakam Yajamahe...", "count": "108 times"}]'::jsonb,
    'Goddess Parvati performed intense penance in Shravan to marry Lord Shiva.',
    '[{"label": "Shubh Somvar Muhurat", "value": "06:00 AM - 09:00 AM"}]'::jsonb,
    '{"name": "Shravan Rudrabhishek Puja", "price": "₹3,500", "duration": "90 mins", "route": "/all_pujas"}'::jsonb
)
ON CONFLICT (date_key) DO UPDATE SET
    title = EXCLUDED.title,
    date_str = EXCLUDED.date_str,
    deity = EXCLUDED.deity,
    deity_label = EXCLUDED.deity_label,
    vrat_type = EXCLUDED.vrat_type,
    importance = EXCLUDED.importance,
    one_liner = EXCLUDED.one_liner,
    description = EXCLUDED.description,
    why_observe = EXCLUDED.why_observe,
    benefits = EXCLUDED.benefits,
    how_to_perform = EXCLUDED.how_to_perform,
    food_guidelines = EXCLUDED.food_guidelines,
    mantras_prayers = EXCLUDED.mantras_prayers,
    vrat_katha = EXCLUDED.vrat_katha,
    puja_timings = EXCLUDED.puja_timings,
    recommended_puja = EXCLUDED.recommended_puja,
    updated_at = now();

