const { createClient } = require('@supabase/supabase-js');
const dns = require('dns');
dns.setDefaultResultOrder('ipv4first');

const supabaseUrl = 'https://vjkwmefdutltwccpgnny.supabase.co';
const supabaseKey = 'sb_publishable_gZzOlAfCHCDDgdTbMop8zQ_18bQRX0L';
const supabase = createClient(supabaseUrl, supabaseKey);

const categories = [
  {
    title: 'HEALTH\nPROBLEMS',
    color: '#b91c1c',
    gradient_start: '#fee2e2',
    gradient_end: '#fecaca',
    image_url: 'https://pub-3027d8d3defe4496978413d3c630aa44.r2.dev/health_problem.png',
    sort_order: 1
  },
  {
    title: 'WEALTH &\nMONEY',
    color: '#a16207',
    gradient_start: '#fef9c3',
    gradient_end: '#fef08a',
    image_url: 'https://pub-3027d8d3defe4496978413d3c630aa44.r2.dev/Welth&Money.png',
    sort_order: 2
  },
  {
    title: 'JOB &\nCAREER',
    color: '#1d4ed8',
    gradient_start: '#dbeafe',
    gradient_end: '#bfdbfe',
    image_url: 'https://pub-3027d8d3defe4496978413d3c630aa44.r2.dev/Job&career.png',
    sort_order: 3
  },
  {
    title: 'MARRIAGE\n& LOVE',
    color: '#be185d',
    gradient_start: '#fce7f3',
    gradient_end: '#fbcfe8',
    image_url: 'https://pub-3027d8d3defe4496978413d3c630aa44.r2.dev/Marriage&Love.png',
    sort_order: 4
  },
  {
    title: 'GRAH DOSH\n& SHANTI',
    color: '#6d28d9',
    gradient_start: '#f3e8ff',
    gradient_end: '#e9d5ff',
    image_url: 'https://pub-3027d8d3defe4496978413d3c630aa44.r2.dev/grah_dosh.png',
    sort_order: 5
  },
  {
    title: 'EDUCATION\n& FOCUS',
    color: '#0d9488',
    gradient_start: '#ccfbf1',
    gradient_end: '#99f6e4',
    image_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=300&q=80',
    sort_order: 6
  }
];

const pujas = [
  // HEALTH
  {
    title: 'Maha Mrityunjaya Healing Havan',
    original_price: '₹4,500',
    offer_price: '₹1,500',
    rating: '4.9',
    reviews: '480',
    provider: 'Ujjain Mahakal Priests',
    image_url: 'https://images.unsplash.com/photo-1616038242814-a6eac7845d88?auto=format&fit=crop&w=600&q=80',
    tag: 'Aarogya Seva',
    requirement: '90 mins',
    problem_category: 'Health',
    tagline: 'Divine healing shield for severe health recovery & longevity.',
    benefits: '• Neutralizes chronic diseases & boosts vital energy\n• Instills strong mental peace and eliminates fear of death\n• Shields your family from sudden accidents and negative vibrations',
    steps: '• Sankalp chanting with gotra & birth star\n• Recitation of 11,000 Mahamrityunjaya mantras by temple acharyas\n• Sacred wood Havan offering & final Bhasma Aarti',
    samagri: 'Amrita herbs, black sesame, pure ghee, wood blocks, and holy ash.',
    pandit: 'Acharya Somesh Shastri',
    temple: 'Mahakaleshwar Temple, Ujjain',
    prasad: 'Blessed Mahakal Bhasma packet, energized 5-mukhi Rudraksha, and sacred red thread.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,500',
    single_original_price: '₹4,500',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹3,000',
    family_original_price: '₹9,000',
    sort_order: 1
  },
  {
    title: 'Dhanvantari Rog Nivaran Homa',
    original_price: '₹3,100',
    offer_price: '₹1,100',
    rating: '4.8',
    reviews: '320',
    provider: 'Kerala Ayurvedic Acharyas',
    image_url: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=600&q=80',
    tag: 'Health Shield',
    requirement: '60 mins',
    problem_category: 'Health',
    tagline: 'Invoke Dhanvantari, the doctor of Gods, to cure deep physical ailments.',
    benefits: '• Enhances immunity and rejuvenates physical body energy\n• Minimizes recovery time post surgery or long illnesses\n• Brings divine medicinal vibes into the household',
    steps: '• Dhanvantari Avahanam & herb dedication\n• Chanting of Dhanvantari Beej Mantras 108 times\n• Offering of 108 medicinal herbs in Havan fire',
    samagri: 'Dhanvantari herbs, lotus petals, cardamom, pure honey, and cow ghee.',
    pandit: 'Pandit Unnikrishnan Namboothiri',
    temple: 'Dhanvantari Temple, Nelluvai, Kerala',
    prasad: 'Consecrated Dhanvantari copper card, herbal healing powder, and sacred yellow thread.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,100',
    single_original_price: '₹3,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹2,200',
    family_original_price: '₹6,200',
    sort_order: 2
  },
  {
    title: 'Shiv Kripa Rog Nashak Puja',
    original_price: '₹2,100',
    offer_price: '₹750',
    rating: '4.9',
    reviews: '610',
    provider: 'Kashi Vedic Pandits',
    image_url: 'https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?auto=format&fit=crop&w=600&q=80',
    tag: 'Vedic Protection',
    requirement: '45-60 mins',
    problem_category: 'Health',
    tagline: 'Purify negative karma, restore mental sanity & cure nervous weakness.',
    benefits: '• Resolves psychosomatic disorders & mental anxiety\n• Dissolves past negative karma causing physical sufferances\n• Welcomes Shiva\'s divine protective energies to standard health',
    steps: '• Shodashopachara Puja of Shiva Lingam\n• Milk, honey & Gangajal Rudrabhishek by holy acharyas\n• Recitation of Rudram & final Kashi Ganga Aarti',
    samagri: 'Gangajal, organic honey, fresh bilva leaves, sugarcane juice, and white sandalwood.',
    pandit: 'Acharya Raman Shastri',
    temple: 'Kashi Vishwanath Shrine, Varanasi',
    prasad: 'Holy Ganga water bottle, Shiva pocket card, and dry sweet peda prasad.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹750',
    single_original_price: '₹2,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,500',
    family_original_price: '₹4,200',
    sort_order: 3
  },

  // WEALTH
  {
    title: 'Kanakadhara Lakshmi Yagya',
    original_price: '₹5,100',
    offer_price: '₹2,100',
    rating: '4.9',
    reviews: '410',
    provider: 'Sree Padmanabha Scholars',
    image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80',
    tag: 'Gold Flow',
    requirement: '90 mins',
    problem_category: 'Wealth',
    tagline: 'Manifest gold, resolve financial stagnation, and invoke Lakshmi\'s grace.',
    benefits: '• Opens locked cash flows and creates new income channels\n• Attracts gold, property, and vehicle purchase opportunities\n• Fills the household with continuous prosperity and luck',
    steps: '• Lakshmi Avahanam & gold-plated coins shringar\n• Recitation of Kanakadhara Stotram 18 times\n• Havan offering with lotus seeds & cow ghee',
    samagri: 'Lotus seed mala, fresh red lotus flowers, saffron threads, and aromatic perfumes.',
    pandit: 'Acharya Padmanabhan',
    temple: 'Sree Padmanabhaswamy Temple, Kerala',
    prasad: 'Energized Kanakadhara Yantra card, sacred yellow thread, and dry fruit panchamrit.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹2,100',
    single_original_price: '₹5,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹4,200',
    family_original_price: '₹10,200',
    sort_order: 1
  },
  {
    title: 'Ashta Lakshmi Dhan Vriddhi Homa',
    original_price: '₹3,500',
    offer_price: '₹1,250',
    rating: '4.8',
    reviews: '380',
    provider: 'Mahalakshmi Priests',
    image_url: 'https://images.unsplash.com/photo-1609137144814-6c3614275f7e?auto=format&fit=crop&w=600&q=80',
    tag: 'Abundance',
    requirement: '60-75 mins',
    problem_category: 'Wealth',
    tagline: 'Invoke all 8 forms of Laxmi for complete wealth and debt clearance.',
    benefits: '• Clears heavy debts and bad financial decisions\n• Brings success in trading, retail, and business partnerships\n• Resolves family property disputes and legal money blocks',
    steps: '• Ashta Lakshmi worship with 8 unique flower setups\n• Chanting of Lakshmi Ashtothra Shatanamavali\n• Special Havan offering with sweet kheer',
    samagri: 'Red rose petals, yellow cowries, raw turmeric, dry coconut kernel, and camphor.',
    pandit: 'Pandit Ramesh Chaturvedi',
    temple: 'Mahalakshmi Temple, Kolhapur',
    prasad: 'Consecrated copper Shree Yantra, blessed red thread, and sweet sugar candies.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,250',
    single_original_price: '₹3,500',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹2,500',
    family_original_price: '₹7,000',
    sort_order: 2
  },
  {
    title: 'Kuber Bhandari Wealth Puja',
    original_price: '₹2,500',
    offer_price: '₹850',
    rating: '4.9',
    reviews: '270',
    provider: 'Kuber Temple Acharyas',
    image_url: 'https://images.unsplash.com/photo-1554224155-169641357599?q=80&w=400',
    tag: 'Savings Growth',
    requirement: '45 mins',
    problem_category: 'Wealth',
    tagline: 'Worship the treasurer of Gods to stabilize wealth and multiply savings.',
    benefits: '• Stabilizes current income & prevents sudden financial leakages\n• Multiplies investments and family savings\n• Instills business expansion ideas and wealth wisdom',
    steps: '• Lord Kuber Avahanam & coin box empowerment\n• Chanting of Kuber Dhanada Mantras 108 times\n• Offering of green gram and saffron rice',
    samagri: 'Kuber key, green grains, cardamom, pure ghee, and copper vessel.',
    pandit: 'Acharya Kuber Prasad',
    temple: 'Kuber Bhandari Temple, Gujarat',
    prasad: 'Energized Kuber key card, yellow thread, and temple chandan powder.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹850',
    single_original_price: '₹2,500',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,600',
    family_original_price: '₹5,000',
    sort_order: 3
  },

  // JOB & CAREER
  {
    title: 'Surya Dev Vyavasaya Vijaya Homa',
    original_price: '₹2,500',
    offer_price: '₹851',
    rating: '4.8',
    reviews: '240',
    provider: 'Konark Aditya Acharyas',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    tag: 'Government Job',
    requirement: '60 mins',
    problem_category: 'Job & Career',
    tagline: 'Gain leadership command, respect, and promotions in government jobs.',
    benefits: '• Accelerates job promotions and clears career obstacles\n• Increases confidence, communication skills, and social respect\n• Assists in securing government posts & political support',
    steps: '• Surya Dev Avahanam & copper pot water offering\n• Chanting of Aditya Hrudaya Stotram with name sankalp\n• Red chandan & wheat offerings in sacred Homa',
    samagri: 'Red sandalwood paste, wheat grains, copper plates, and red hibiscus flowers.',
    pandit: 'Pandit Bhaskar Shastri',
    temple: 'Konark Sun Temple Circle, Odisha',
    prasad: 'Energized Surya copper coin card, red chandan powder, and wheat seeds.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹851',
    single_original_price: '₹2,500',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,700',
    family_original_price: '₹5,000',
    sort_order: 1
  },
  {
    title: 'Ganesh Karyasiddhi Vighnaharta Homa',
    original_price: '₹1,501',
    offer_price: '₹501',
    rating: '4.9',
    reviews: '350',
    provider: 'Siddhivinayak Temple Priests',
    image_url: 'https://images.unsplash.com/photo-1567591974574-e8b28634e35f?auto=format&fit=crop&w=600&q=80',
    tag: 'Obstacle Removal',
    requirement: '45-60 mins',
    problem_category: 'Job & Career',
    tagline: 'Dissolve blocks in career start, business launches, and interviews.',
    benefits: '• Dissolves start-up bottlenecks and business delays\n• Enhances logical reasoning, intelligence, and interview performance\n• Brings Lord Ganesha\'s blessings for auspicious career starts',
    steps: '• Ganesh Avahanam & Gotra Sankalp\n• Recitation of Ganesh Atharvashirsha by holy pandits\n• Sweet modak and Durva grass offering',
    samagri: 'Durva grass, fresh modaks, red vermilion, and pure ghee.',
    pandit: 'Acharya Vinayak Shastri',
    temple: 'Prabhadevi Siddhivinayak Mandir, Mumbai',
    prasad: 'Vacuum-sealed box of holy Modaks, consecrated red thread, and Ganesha card.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹501',
    single_original_price: '₹1,501',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,000',
    family_original_price: '₹3,000',
    sort_order: 2
  },
  {
    title: 'Hanuman Bajrangbal Success Path',
    original_price: '₹999',
    offer_price: '₹351',
    rating: '4.8',
    reviews: '410',
    provider: 'Ayodhya Garhi Priests',
    image_url: 'https://images.unsplash.com/photo-1615818499660-30bb587f48d9?auto=format&fit=crop&w=600&q=80',
    tag: 'Career Strength',
    requirement: '30 mins',
    problem_category: 'Job & Career',
    tagline: 'Overcome workplace politics, target pressure, and win competitive exams.',
    benefits: '• Eliminates fear of failure & performance anxiety\n• Shields you from corporate jealousy and workplace politics\n• Boosts courage, memory power, and physical health',
    steps: '• Lord Hanuman Avahanam & gotra Sankalp\n• Complete Hanuman Chalisa & Bajrang Baan recitations\n• Sindoor shringar and oil lamp offering',
    samagri: 'Orange vermilion (sindoor), mustard oil, dynamic tulsi leaf mala, and gram laddoos.',
    pandit: 'Acharya Bajrang Shastri',
    temple: 'Hanuman Garhi Temple, Ayodhya',
    prasad: 'Energized Hanuman pocket card, Garhi sacred orange paste, and holy tulsi seeds.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹351',
    single_original_price: '₹999',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹700',
    family_original_price: '₹2,000',
    sort_order: 3
  },

  // MARRIAGE & LOVE
  {
    title: 'Uma Maheshwar Marriage Delay Puja',
    original_price: '₹3,500',
    offer_price: '₹1,250',
    rating: '4.9',
    reviews: '290',
    provider: 'Kashi Shiva-Parvati Shrine',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=600&q=80',
    tag: 'Marriage Match',
    requirement: '75 mins',
    problem_category: 'Marriage & Love',
    tagline: 'Perfect divine intervention to resolve marriage delays and match blocks.',
    benefits: '• Neutralizes delayed marriage obstacles (Manglik/planetary blocks)\n• Attracts a loving, compatible, and loyal life partner\n• Grants Shiva-Parvati\'s joint blessings for long-lasting union',
    steps: '• Shiva-Parvati joint Avahanam & Gathbandhan ritual\n• Chanting of Uma Maheshwar Stotram 108 times\n• Flower garland exchange tribute',
    samagri: 'Red chunri, yellow thread, coconut, turmeric bulbs, and fresh rose garlands.',
    pandit: 'Acharya Parvati Prasad',
    temple: 'Kashi Vishwanath Corridor, Varanasi',
    prasad: 'Uma-Maheshwar pocket card, sacred red thread, and Vrindavan chandan.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,250',
    single_original_price: '₹3,500',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹2,500',
    family_original_price: '₹7,000',
    sort_order: 1
  },
  {
    title: 'Radha Krishna Prem Seva Path',
    original_price: '₹2,100',
    offer_price: '₹751',
    rating: '4.9',
    reviews: '430',
    provider: 'Vrindavan Dham Goswamis',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=600&q=80',
    tag: 'Relationship Harmony',
    requirement: '45 mins',
    problem_category: 'Marriage & Love',
    tagline: 'Resolve differences, heal breakups, and restore trust in love.',
    benefits: '• Dissolves misunderstandings, hot arguments, and cold wars\n• Reconnects broken relationship channels and restores love trust\n• Fills your home with sweet, peaceful vibes of devotion',
    steps: '• Radha Krishna Shringar & fresh flower decoration\n• Recitation of Madhurashtakam & Prem Beej Mantras\n• Sweet modak & tulsi offering',
    samagri: 'Jasmine flowers, holy tulsi leaves, Vrindavan pedas, and sweet perfumes.',
    pandit: 'Pandit Banke Lal Goswami',
    temple: 'Banke Bihari Temple, Vrindavan',
    prasad: 'Blessed Radha-Krishna card, Vrindavan chandan powder, and holy tulsi seeds.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹751',
    single_original_price: '₹2,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,500',
    family_original_price: '₹4,200',
    sort_order: 2
  },
  {
    title: 'Swayamvara Parvathi Shrinagar Puja',
    original_price: '₹4,500',
    offer_price: '₹1,500',
    rating: '4.8',
    reviews: '180',
    provider: 'Madurai Meenakshi Acharyas',
    image_url: 'https://images.unsplash.com/photo-1561571994-3c61c554181a?auto=format&fit=crop&w=600&q=80',
    tag: 'Ideal Partner',
    requirement: '60 mins',
    problem_category: 'Marriage & Love',
    tagline: 'Powerful ancient ritual to attract your desired partner and resolve fights.',
    benefits: '• Attracts desired spouse matches with good social backgrounds\n• Removes family resistance to love marriage approvals\n• Restores domestic warmth and prevents post-marriage conflicts',
    steps: '• Goddess Meenakshi Avahanam & cosmetic shringar\n• Chanting of Swayamvara Parvathi Mantra 1008 times\n• Red vermilion (Kumkum) archana',
    samagri: 'Sandalwood paste, turmeric, kumkum, bangles, and fresh jasmine garlands.',
    pandit: 'Acharya Sundararajan',
    temple: 'Madurai Meenakshi Temple, Tamil Nadu',
    prasad: 'Blessed Meenakshi kumkum pack, holy yellow thread, and dry sugar candies.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,500',
    single_original_price: '₹4,500',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹3,000',
    family_original_price: '₹9,000',
    sort_order: 3
  },

  // GRAH DOSH
  {
    title: 'Navgrah Dosha Nivaran Mahayagya',
    original_price: '₹4,500',
    offer_price: '₹1,500',
    rating: '4.7',
    reviews: '175',
    provider: 'Kashi Vedic Pandits',
    image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    tag: '9 Planet Balance',
    requirement: '90 mins',
    problem_category: 'Grah Dosh',
    tagline: 'Harmonize Rahu, Ketu, Saturn and balance all 9 planets in your chart.',
    benefits: '• Decreases malefic planetary dashas (Rahu, Ketu, Saturn, etc.)\n• Harmonizes relationships, career flow, and financial blocks\n• Minimizes unexpected troubles and builds positive planetary luck',
    steps: '• Navagraha Avahanam & colorful grains layout\n• Chanting of Navagraha Stotram & separate planet mantras\n• Nine-color flower dedication & final Havan',
    samagri: 'Nine-color cloth blocks, nine different grains, pure camphor, and ghee lamps.',
    pandit: 'Acharya Devrath Joshi',
    temple: 'Navagraha Temple, Guwahati, Assam',
    prasad: 'Energized Navagraha copper yantra, planet-blessed black thread, dry fruit mewa.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,500',
    single_original_price: '₹4,500',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹3,000',
    family_original_price: '₹9,000',
    sort_order: 1
  },
  {
    title: 'Shani Grah Shanti Oil Abhishekam',
    original_price: '₹2,500',
    offer_price: '₹851',
    rating: '4.7',
    reviews: '480',
    provider: 'Shingnapur Shani Acharyas',
    image_url: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=600&q=80',
    tag: 'Sade Sati Remedy',
    requirement: '45 mins',
    problem_category: 'Grah Dosh',
    tagline: 'Calm the malefic effects of Saturn Sade Sati, Dhaiya, and Kantak Shani.',
    benefits: '• Decreases obstacles, financial constraints, and delays caused by Saturn\n• Restores mental calm and protects from accidents/sudden falls\n• Enhances discipline, hard work reward, and business stability',
    steps: '• Shani Dev Avahanam & black sesame oil bath dedication\n• Recitation of Shani Stotram & Shani Mantra with name sankalp\n• Iron ring dedication & final protection aarti',
    samagri: 'Black sesame oil, black cloth, iron nails, blue flowers, and black gram.',
    pandit: 'Acharya Shani Dev Shastry',
    temple: 'Shani Shingnapur Mandir, Maharashtra',
    prasad: 'Energized iron Shani ring, sacred black thread, and temple chandan powder.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹851',
    single_original_price: '₹2,500',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,700',
    family_original_price: '₹5,000',
    sort_order: 2
  },
  {
    title: 'Rahu-Ketu Shanti Dosha Nivaran',
    original_price: '₹3,100',
    offer_price: '₹1,100',
    rating: '4.8',
    reviews: '290',
    provider: 'Kalahasti Temple Scholars',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=600&q=80',
    tag: 'Kaal Sarp Remedy',
    requirement: '60 mins',
    problem_category: 'Grah Dosh',
    tagline: 'Remedy for Kaal Sarp Dosh, sudden losses, confusion, and fear.',
    benefits: '• Dissolves Kaal Sarp Dosha effects and recurring bad dreams\n• Overcomes sudden losses in trade, stock trading, and lawsuits\n• Clears mental confusion, stress, and anxiety triggers',
    steps: '• Rahu & Ketu Avahanam with metal snake idols\n• Rahu-Ketu Stotram chanting and gotra Sankalp\n• Special black sesame and mustard seed offering',
    samagri: 'Silver Rahu-Ketu snake icons, black sesame, mustard seeds, and urad dal.',
    pandit: 'Acharya Kalahastheeswara',
    temple: 'Sri Kalahasteeswara Temple, Andhra Pradesh',
    prasad: 'Blessed copper snake ring, sacred black thread, and Kalahasti vibhuti.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,100',
    single_original_price: '₹3,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹2,200',
    family_original_price: '₹6,200',
    sort_order: 3
  },

  // EDUCATION
  {
    title: 'Basar Saraswati Vidya Homa',
    original_price: '₹1,501',
    offer_price: '₹501',
    rating: '4.8',
    reviews: '190',
    provider: 'Basar Temple Scholars',
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    tag: 'Exam Success',
    requirement: '45 mins',
    problem_category: 'Education',
    tagline: 'Boost concentration, intellect, and memory power for academic success.',
    benefits: '• Improves memory power, logical skills, and educational performance\n• Enhances artistic talents, musical flow, and communication skills\n• Establishes focus and blocks exams-related anxiety',
    steps: '• Saraswati Devi Avahanam & book/pen dedication\n• Chanting of Saraswati Beej mantras with name sankalp\n• White flower tribute & final lamp aarti',
    samagri: 'White marigold flowers, chandan paste, yellow rice, and cardamom sweets.',
    pandit: 'Pandit Sharad Dwivedi',
    temple: 'Basar Gnana Saraswathi Mandir, Telangana',
    prasad: 'Energized copper Saraswati Yantra card, sacred yellow thread, and sweet sugar candies.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹501',
    single_original_price: '₹1,501',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,000',
    family_original_price: '₹3,000',
    sort_order: 1
  },
  {
    title: 'Hayagriva Medha Buddhi Puja',
    original_price: '₹2,100',
    offer_price: '₹750',
    rating: '4.9',
    reviews: '140',
    provider: 'Srirangam Vedic Scholars',
    image_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=300&q=80',
    tag: 'Analytical Skills',
    requirement: '60 mins',
    problem_category: 'Education',
    tagline: 'Invoke the horse-necked Vishnu for high analytical and logical skills.',
    benefits: '• Enhances analytical thinking, mathematical skills, and coding logic\n• Bestows clarity in speech, debating power, and quick memory retrieval\n• Helps students prepare for tough competitive exams (IIT/IAS/NEET)',
    steps: '• Lord Hayagriva Avahanam & white flower archana\n• Chanting of Hayagriva Upanishad verses with child\'s name\n• Offering of sweet cardamoms and honey',
    samagri: 'Cardamom garland, white lotus flowers, pure honey, and sacred books.',
    pandit: 'Acharya Sriranganatha Bhattar',
    temple: 'Sri Ranganathaswamy Temple, Srirangam',
    prasad: 'Energized Hayagriva copper card, sweet dry fruits, and sacred yellow thread.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹750',
    single_original_price: '₹2,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,500',
    family_original_price: '₹4,200',
    sort_order: 2
  },
  {
    title: 'Guru Brihaspati Gyan Vardhak Path',
    original_price: '₹3,100',
    offer_price: '₹1,100',
    rating: '4.8',
    reviews: '160',
    provider: 'Alangudi Guru Acharyas',
    image_url: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?auto=format&fit=crop&w=600&q=80',
    tag: 'Higher Education',
    requirement: '45-60 mins',
    problem_category: 'Education',
    tagline: 'Worship Jupiter for success in research, higher education, and wisdom.',
    benefits: '• Boosts wisdom, decision-making capabilities, and maturity\n• Ensures success in PhD, research, and international higher studies\n• Calms down planetary blocks hindering mental growth',
    steps: '• Guru Brihaspati Dev Avahanam with yellow flowers\n• Recitation of Guru Stotram & Brihaspati Kavach\n• Chana dal and yellow cloth tribute',
    samagri: 'Chana dal, yellow cloth, yellow flowers, turmeric paste, and ghee lamp.',
    pandit: 'Acharya Brihaspati Shastri',
    temple: 'Apatsahayesvarar Temple, Alangudi (Guru Sthalam)',
    prasad: 'Blessed yellow thread, Guru yantra card, and organic turmeric powder.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,100',
    single_original_price: '₹3,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹2,200',
    family_original_price: '₹6,200',
    sort_order: 3
  }
];

async function seed() {
  console.log('Clearing old life_problems and problem_poojas...');
  try {
    // 1. Clear tables
    const { error: delPoojasErr } = await supabase
      .from('problem_poojas')
      .delete()
      .neq('id', '00000000-0000-0000-0000-000000000000');
    if (delPoojasErr) throw delPoojasErr;
    console.log('Old problem_poojas cleared.');

    const { error: delProblemsErr } = await supabase
      .from('life_problems')
      .delete()
      .neq('id', '00000000-0000-0000-0000-000000000000');
    if (delProblemsErr) throw delProblemsErr;
    console.log('Old life_problems cleared.');

    // 2. Insert Categories
    console.log(`Inserting ${categories.length} Life Problem categories...`);
    const { data: catData, error: insCatErr } = await supabase
      .from('life_problems')
      .insert(categories)
      .select();
    if (insCatErr) throw insCatErr;
    console.log('Successfully inserted categories. Count:', catData.length);

    // 3. Insert Pujas
    console.log(`Inserting ${pujas.length} problem-solution Pujas...`);
    const { data: pujaData, error: insPujaErr } = await supabase
      .from('problem_poojas')
      .insert(pujas)
      .select();
    if (insPujaErr) throw insPujaErr;
    console.log('Successfully inserted problem-solution Pujas. Count:', pujaData.length);

    console.log('Database Seeding Completed Successfully! 🎉');
    process.exit(0);
  } catch (err) {
    console.error('Error seeding database:', err);
    process.exit(1);
  }
}

seed();
