const { createClient } = require('@supabase/supabase-js');
const dns = require('dns');
dns.setDefaultResultOrder('ipv4first');

const supabaseUrl = 'https://vjkwmefdutltwccpgnny.supabase.co';
const supabaseKey = 'sb_publishable_gZzOlAfCHCDDgdTbMop8zQ_18bQRX0L';

const supabase = createClient(supabaseUrl, supabaseKey);

const poojas = [
  {
    title: 'Ganesh Vignaharta Puja',
    original_price: '₹751',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '340',
    provider: 'Siddhivinayak Temple Priests',
    image_url: 'https://images.unsplash.com/photo-1567591974574-e8b28634e35f?auto=format&fit=crop&w=600&q=80',
    tag: 'Success',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Remove obstacles and invoke prosperity. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Dissolves obstacles in career, business, and personal ventures\n• Attracts positive energy and intelligence into your workspace\n• Brings Ganesha\'s direct blessings of wisdom and auspiciousness',
    steps: '1. Ganesha Avahanam & Sankalp chanting with your name/gotra\n2. Ganesh Atharvashirsha path recitation by holy pandits\n3. Modak offering & final Mangal aarti',
    samagri: 'Durva grass, fresh modaks, red hibiscus flowers, red vermilion, and pure ghee.',
    pandit: 'Acharya Vinayak Shastri - Siddhivinayak Temple Associate Priest',
    temple: 'Prabhadevi Siddhivinayak Mandir, Mumbai',
    prasad: 'Vacuum-sealed box containing holy Modak sweets, consecrated red thread, and Siddhivinayak pocket picture card.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Maha Laxmi Wealth Puja',
    original_price: '₹999',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '520',
    provider: 'Mahalakshmi Mandir Priests',
    image_url: 'https://images.unsplash.com/photo-1609137144814-6c3614275f7e?auto=format&fit=crop&w=600&q=80',
    tag: 'Wealth',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Attract financial abundance and luxury. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Activates continuous inflows of wealth and business growth\n• Cleanses negative financial blocks and helps in debt clearance\n• Welcomes lasting household abundance and family prosperity',
    steps: '1. Laxmi Aavahan Puja & name-specific Sankalp\n2. Ashta-Laxmi Stotram Recitation by head priests\n3. Sacred Havan offering with lotus seeds',
    samagri: 'Lotus seed mala, saffron threads, red rose petals, and cow ghee.',
    pandit: 'Pandit Ramesh Chaturvedi - Mahalakshmi Head Priest',
    temple: 'Mahalakshmi Temple, Kolhapur',
    prasad: 'Consecrated copper Shree Yantra shield, dry fruit panchamrit, and sacred thread.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Sankat Mochan Hanuman Puja',
    original_price: '₹501',
    offer_price: '₹1',
    rating: '4.8',
    reviews: '410',
    provider: 'Ayodhya Garhi Priest Panel',
    image_url: 'https://images.unsplash.com/photo-1615818499660-30bb587f48d9?auto=format&fit=crop&w=600&q=80',
    tag: 'Protection',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Ward off negative energies and bad health. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Shields your family from evil forces, planetary doshas, and enemies\n• Enhances physical stamina, courage, and mental clarity\n• Restores peace and harmony in turbulent households',
    steps: '1. Lord Hanuman Avahanam & personal gotra Sankalp\n2. Complete Hanuman Chalisa and Bajrang Baan recitations\n3. Sindoor shringar and oil lamp offering',
    samagri: 'Sacred vermilion (sindoor), mustard oil, dynamic tulsi leaf mala, and gram laddoos.',
    pandit: 'Acharya Bajrang Shastri - Hanuman Garhi Senior Acharya',
    temple: 'Hanuman Garhi Temple, Ayodhya',
    prasad: 'Energized Hanuman pocket kavach card, Garhi sacred orange paste, and holy tulsi seeds.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Shiva Kripa Rudra Puja',
    original_price: '₹1200',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '610',
    provider: 'Kashi Vishwanath Priests',
    image_url: 'https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?auto=format&fit=crop&w=600&q=80',
    tag: 'Blessings',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Purify sins and secure health. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Nullifies negative karmic patterns and ancestral debts\n• Grants extreme peace of mind and mental balance\n• Bestows longevity, health, and spiritual awakening',
    steps: '1. Mahadev Avahanam & milk/honey abhishek\n2. Chanting of 108 Shiv Shasranama verses with your name sankalp\n3. Bilvapatra offerings & final Kashi Ganga aarti',
    samagri: 'Sacred Gangajal, organic milk, honey, fresh bilvapatra leaves, and white chandan.',
    pandit: 'Acharya Raman Shastri - Kashi Vishwanath Trust Priest',
    temple: 'Kashi Vishwanath Shrine, Varanasi',
    prasad: 'Holy Gangajal bottle, energized Shiva pocket card, and dry sweet peda prasad.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Saraswati Vidya Puja',
    original_price: '₹650',
    offer_price: '₹1',
    rating: '4.8',
    reviews: '190',
    provider: 'Vedic Gurukul Pandits',
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    tag: 'Education',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Boost concentration and academic success. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Improves memory power, logical skills, and educational performance\n• Enhances artistic talents, musical flow, and communication skills\n• Establishes focus and blocks exams-related anxiety',
    steps: '1. Saraswati Devi Avahanam & book/pen dedication\n2. Chanting of Saraswati Beej mantras with name sankalp\n3. White flower tribute & final lamp aarti',
    samagri: 'White marigold flowers, chandan paste, yellow rice, and cardamom sweets.',
    pandit: 'Pandit Sharad Dwivedi - Gurukul Head Instructor',
    temple: 'Basar Gnana Saraswathi Mandir',
    prasad: 'Energized copper Saraswati Yantra card, sacred yellow thread, and sweet sugar candies.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Shani Dev Shanti Puja',
    original_price: '₹850',
    offer_price: '₹1',
    rating: '4.7',
    reviews: '480',
    provider: 'Shingnapur Shani Priests',
    image_url: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=600&q=80',
    tag: 'Astro',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Reduce Saturn (Shani) Sade Sati effects. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Decreases obstacles, financial constraints, and delays caused by Saturn\n• Restores mental calm and protects from accidents/sudden falls\n• Enhances discipline, hard work reward, and business stability',
    steps: '1. Shani Dev Avahanam & black sesame oil bath dedication\n2. Recitation of Shani Stotram & Shani Mantra with name sankalp\n3. Iron ring dedication & final protection aarti',
    samagri: 'Black sesame oil, black cloth, iron nails, blue flowers, and black gram.',
    pandit: 'Acharya Shani Dev Shastry - Shingnapur Resident Priest',
    temple: 'Shani Shingnapur Mandir, Maharashtra',
    prasad: 'Energized iron Shani ring, sacred black thread, and temple chandan powder.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Durga Raksha Kavach Puja',
    original_price: '₹950',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '290',
    provider: 'Himachal Durga Priests',
    image_url: 'https://images.unsplash.com/photo-1561571994-3c61c554181a?auto=format&fit=crop&w=600&q=80',
    tag: 'Shield',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Divine armor for victory over enemies. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Grants supreme protective shield against black magic and jealousy\n• Helps achieve victory in court disputes and property battles\n• Fosters inner strength and eliminates deep-rooted fears',
    steps: '1. Durga Devi Avahanam & weapon empowerment ritual\n2. Chanting of Durga Saptashati Shlokas with your name/gotra\n3. Red vermilion offering & final high-energy aarti',
    samagri: 'Red chunri, coconut, red vermilion, dry coconut kernel, and camphor.',
    pandit: 'Pandit Somnath Dwivedi - Durga Shrine Acharya',
    temple: 'Jwala Ji Durga Temple, Himachal Pradesh',
    prasad: 'Blessed red Durga chunri, energized copper Durga pocket card, and temple vermilion.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Kanakadhara Lakshmi Puja',
    original_price: '₹1100',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '310',
    provider: 'Sree Padmanabha Pandits',
    image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80',
    tag: 'Gold Flow',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Manifest gold and wealth opportunities. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Invokes the golden shower of wealth and luck into your family\n• Clears business stagnation and opens multiple income streams\n• Bestows luxurious comforts, assets, and vehicle purchases',
    steps: '1. Lakshmi Avahanam & gold-plated coins shringar\n2. Chanting of Kanakadhara Stotram 18 times with name sankalp\n3. Lotus flower dedication & dynamic final aarti',
    samagri: 'Gold-plated coins, fresh lotus flowers, pure honey, and aromatic incense.',
    pandit: 'Acharya Padmanabhan - Padmanabhaswamy Shrine Priest',
    temple: 'Sree Padmanabhaswamy Temple, Kerala',
    prasad: 'Energized Kanakadhara card, sacred yellow thread, and dry sugar candy prasad.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Mahamrityunjaya Arogya Puja',
    original_price: '₹1500',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '670',
    provider: 'Ujjain Mahakal Acharyas',
    image_url: 'https://images.unsplash.com/photo-1616038242814-a6eac7845d88?auto=format&fit=crop&w=600&q=80',
    tag: 'Health',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Recover from severe diseases and bad energy. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Neutralizes severe health threats and heals old illness blocks\n• Eradicates negative energy and mental depression triggers\n• Bestows robust health, high vitality, and a peaceful long life',
    steps: '1. Mahakal Avahanam & personal health gotra Sankalp\n2. Chanting of Mahamrityunjaya Mantra 108 times by Vedic priests\n3. Bhasma shringar tribute & final Ujjain Aarti',
    samagri: 'Sacred bhasma (holy ash), bilva leaves, sesame seeds, and white flowers.',
    pandit: 'Acharya Somesh Shastri - Mahakaleshwar Temple Associate',
    temple: 'Mahakaleshwar Jyotirlinga Mandir, Ujjain',
    prasad: 'Blessed Mahakal Bhasma packet, energized rudraksha bead, and sacred red thread.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Navgrah Shanti Grah Puja',
    original_price: '₹1350',
    offer_price: '₹1',
    rating: '4.8',
    reviews: '550',
    provider: 'Navagraha Dham Pandits',
    image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    tag: 'Astro',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Balance all nine planets in your horoscope. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Decreases malefic planetary dashas (Rahu, Ketu, Saturn, etc.)\n• Harmonizes relationships, career flow, and financial blocks\n• Minimizes unexpected troubles and builds positive planetary luck',
    steps: '1. Navagraha Avahanam & colorful grains layout\n2. Chanting of Navagraha Stotram & separate planet mantras with name sankalp\n3. Nine-color flower dedication & final light rotation',
    samagri: 'Nine-color cloth blocks, nine different grains, pure camphor, and ghee lamps.',
    pandit: 'Acharya Devrath Joshi - Navagraha Shrine Specialist',
    temple: 'Navagraha Temple, Guwahati, Assam',
    prasad: 'Energized Navagraha copper kavach sheet, sacred colored thread, and chandan paste.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Surya Dev Success Puja',
    original_price: '₹700',
    offer_price: '₹1',
    rating: '4.8',
    reviews: '230',
    provider: 'Aditya Dham Acharyas',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    tag: 'Glory',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Enhance leadership, respect, and career glory. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Bestows leadership authority, respect, and high recognition\n• Helps secure government jobs and win political support\n• Heals eye issues, bone weakness, and physical laziness',
    steps: '1. Lord Surya Avahanam & copper vessel water offering\n2. Chanting of Aditya Hrudaya Stotram with name sankalp\n3. Red chandan and wheat offerings & final sun aarti',
    samagri: 'Red sandal paste, wheat grains, copper plates, and red flowers.',
    pandit: 'Pandit Bhaskar Shastri - Surya Shrine Scholar',
    temple: 'Konark Sun Temple Circle, Odisha',
    prasad: 'Energized Surya copper coin card, red chandan powder, and wheat seeds.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Radha Krishna Prem Puja',
    original_price: '₹800',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '430',
    provider: 'Vrindavan Dham Priests',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=600&q=80',
    tag: 'Love',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Resolve relationship differences and find love. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Restores deep love, understanding, and trust in relationships\n• Resolves marriage delays and matches you with a good partner\n• Fills your home with peaceful devotional vibrations and joy',
    steps: '1. Radha Krishna Shringar & fresh flower decoration\n2. Chanting of Madhurashtakam & Prem mantras with name/gotra sankalp\n3. Tulsi leaf dedication & Vrindavan sweet modak offering',
    samagri: 'Fresh rose petals, dynamic tulsi leaves, vrindavan pedas, and aromatic perfume.',
    pandit: 'Pandit Banke Lal Goswami - Vrindavan Head Priest Associate',
    temple: 'Banke Bihari Temple, Vrindavan',
    prasad: 'Blessed Radha-Krishna pocket card, vrindavan chandan powder, and tulsi leaves.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Kala Bhairav Protection Puja',
    original_price: '₹1150',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '380',
    provider: 'Bhairav Mandir Priests',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=600&q=80',
    tag: 'Protection',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Eliminate toxic threats, lawsuits, and bad luck. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Eradicates toxic people, court lawsuits, and bad luck influences\n• Acts as a severe shield against sudden planetary accidents\n• Bestows absolute fearlessness and restores self-confidence',
    steps: '1. Lord Kala Bhairav Avahanam & black thread offering\n2. Chanting of Bhairav Ashtakam with name/gotra sankalp\n3. Mustard oil lamp illumination & dynamic final aarti',
    samagri: 'Mustard oil, black thread, coconut, standard liquor essence, and black raisins.',
    pandit: 'Acharya Kala Bhairav Shastri - Ujjain Bhairav Temple Priest',
    temple: 'Kaal Bhairav Temple, Ujjain',
    prasad: 'Energized black Bhairav thread, sacred ash (bhasma), and oil lamp wick.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Baglamukhi Shatru Nashini Puja',
    original_price: '₹1800',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '270',
    provider: 'Baglamukhi Dham Pandits',
    image_url: 'https://images.unsplash.com/photo-1542856391-010fb87dcfed?auto=format&fit=crop&w=600&q=80',
    tag: 'Shield',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Silence toxic gossip, false cases, and business enemies. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Paralyzes the malefic intentions of enemies and silences gossip\n• Protects from legal losses and helps secure quick courtroom victories\n• Enhances administrative power and leadership command',
    steps: '1. Devi Baglamukhi Avahanam & yellow cloth shringar\n2. Chanting of Baglamukhi Beej mantras with name/gotra sankalp\n3. Turmeric and yellow flower homam offerings',
    samagri: 'Turmeric roots, yellow cloth, yellow mustard seeds, and yellow sweets.',
    pandit: 'Acharya Pitambar Shastri - Baglamukhi Shrine Specialist',
    temple: 'Baglamukhi Mandir, Datia',
    prasad: 'Energized yellow Baglamukhi thread, yellow turmeric paste, and sweet gram pedas.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Sai Baba Blessings Puja',
    original_price: '₹500',
    offer_price: '₹1',
    rating: '4.8',
    reviews: '560',
    provider: 'Shirdi Sai Associates',
    image_url: 'https://images.unsplash.com/photo-1626291662923-5eeef73d4411?auto=format&fit=crop&w=600&q=80',
    tag: 'Faith',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Fulfill wishes and establish peace. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Fulfills personal wishes, restores family peace, and cures stress\n• Removes domestic financial crisis and grants stability\n• Instills absolute faith (Shraddha) and patience (Saburi) in career',
    steps: '1. Sai Baba Avahanam & flower garland shringar\n2. Reading of Sai Satcharitra chapters & beej mantras with name sankalp\n3. Sacred Udi (ash) offering & final sweet modak aarti',
    samagri: 'Yellow rose garland, incense sticks, fresh fruits, and holy udi powder.',
    pandit: 'Pandit Shirdi Lal Goswami - Sai Sansthan Associate Priest',
    temple: 'Shirdi Sai Mandir Circle, Maharashtra',
    prasad: 'Blessed Shirdi Sai Udi (holy ash) packet, Sai pocket photo card, and dry sweet prasad.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Ganga Aarti & Tarpan Puja',
    original_price: '₹600',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '490',
    provider: 'Haridwar Ganga Priests',
    image_url: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=600&q=80',
    tag: 'Purification',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Attain ancestor peace and personal purification. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Pacifies ancestral pitru doshas and seeks family growth blessings\n• Purifies your subtle body, mind, and home environment\n• Attracts positive cosmic flow and destroys old bad luck blocks',
    steps: '1. Ganga Devi Avahanam & water abhishek with your name/gotra\n2. Ganga Stotram chanting & specific tarpan mantra recitation\n3. Grand brass lamp double Aarti dedication at Ganges bank',
    samagri: 'Brass lamp, camphor, holy flowers, barley seeds, black sesame, and sweets.',
    pandit: 'Acharya Gangadhar Shastri - Haridwar Ganga Aarti Head Priest',
    temple: 'Har Ki Pauri, Haridwar, Uttarakhand',
    prasad: 'Pure Gangajal bottle, sacred red thread, and temple dry fruit sweets.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Karthikeya Victory Puja',
    original_price: '₹750',
    offer_price: '₹1',
    rating: '4.8',
    reviews: '170',
    provider: 'Palani Murugan Priests',
    image_url: 'https://images.unsplash.com/photo-1560759226-14da22a6438a?auto=format&fit=crop&w=600&q=80',
    tag: 'Victory',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Defeat negative entities, gain wisdom, and win exams. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Bestows absolute wisdom, intelligence, and high focus\n• Helps win athletic competitions and educational exams\n• Wards off court opponents and cleanses old debts',
    steps: '1. Lord Murugan Avahanam & sacred milk abhishek\n2. Chanting of Kartikeya Gayatri and Kavacham with name/gotra sankalp\n3. Camphor lamp illumination & final flower dedication',
    samagri: 'Pure milk, sandalwood paste, yellow flowers, and vibhuti powder.',
    pandit: 'Acharya Murugan Swami - Palani Senior Priest Associate',
    temple: 'Palani Murugan Mandir, Tamil Nadu',
    prasad: 'Energized Murugan coin card, sacred temple vibhuti (holy ash), and yellow thread.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Bhairavi Shatru Shanti Puja',
    original_price: '₹1250',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '330',
    provider: 'Vedic Bhairavi Priests',
    image_url: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?auto=format&fit=crop&w=600&q=80',
    tag: 'Shield',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Overcome dark energy, domestic fear, and property disputes. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Protects your space from dark spirits, evil eye, and lawsuits\n• Establishes strong domestic protection for your kids and house\n• Promotes sudden material success and removes health blockages',
    steps: '1. Devi Bhairavi Avahanam & vermilion shringar\n2. Chanting of Bhairavi Kavacham & stotram with name sankalp\n3. Coconut breaking & final protection deepam aarti',
    samagri: 'Red vermilion, mustard seeds, dry coconut, red flowers, and black gram.',
    pandit: 'Pandit Bhairav Dwivedi - Bhairavi Dham Priest Associate',
    temple: 'Linga Bhairavi Circle, Tamil Nadu',
    prasad: 'Energized Bhairavi copper pocket card, red chandan paste, and holy black thread.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Annapurna Family Prosperity Puja',
    original_price: '₹700',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '280',
    provider: 'Kashi Annapurna Priests',
    image_url: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?auto=format&fit=crop&w=600&q=80',
    tag: 'Prosperity',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Guarantee food abundance, health, and domestic harmony. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Ensures your family kitchen is always blessed with food abundance\n• Promotes robust digestive health, longevity, and metabolic flow\n• Eradicates domestic discords and welcomes absolute happiness',
    steps: '1. Goddess Annapurna Avahanam & dynamic grain dedication\n2. Annapurna Stotram chanting & name/gotra sankalp\n3. Pure cow ghee sweets offering & final Mangal aarti',
    samagri: 'Wheat, rice grains, green gram, pure ghee sweets, and yellow flowers.',
    pandit: 'Acharya Somnath Goswami - Annapurna Mandir Priest',
    temple: 'Annapurna Shrine, Varanasi, Uttar Pradesh',
    prasad: 'Energized Annapurna pocket card, sacred yellow thread, and blessed rice grains.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  },
  {
    title: 'Vishnu Sahasranama Puja',
    original_price: '₹1000',
    offer_price: '₹1',
    rating: '4.9',
    reviews: '390',
    provider: 'Srirangam Vedic Pandits',
    image_url: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=600&q=80',
    tag: 'Blessings',
    requirement: 'Book for ₹1 to claim video',
    category: 'General',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Fulfill wishes, balance stars, and gain wealth. A certified pandit performs the puja in your name for just ₹1, and you receive the recorded video.',
    benefits: '• Balances all astrological planetary doshas and cures blockages\n• Grants extreme family prosperity, name, and spiritual success\n• Invokes the protective shields of Lord Narayana over your health',
    steps: '1. Lord Vishnu Avahanam & Tulsi leaf garland shringar\n2. Recitation of complete 1,000 names of Lord Vishnu with your gotra sankalp\n3. Dry fruit prasad offerings & final lamp standard aarti',
    samagri: 'Fresh tulsi leaf garland, yellow sandal paste, dry fruits, and aromatic incense.',
    pandit: 'Acharya Ranganatha Bhattar - Ranganathaswamy Mandir Scholar',
    temple: 'Sri Ranganathaswamy Temple, Srirangam',
    prasad: 'Blessed Tulsi leaves, energized Vishnu copper card, and sacred yellow thread.',
    other_info: 'Recorded video proof of your name/gotra sankalp chanting will be sent on your WhatsApp within 24 hours of puja completion.',
    translations: {}
  }
];

async function seed() {
  console.log('Clearing old ₹1 Pujas...');
  try {
    const { error: clearErr } = await supabase
      .from('one_rupee_poojas')
      .delete()
      .neq('id', '00000000-0000-0000-0000-000000000000'); // Delete all

    if (clearErr) throw clearErr;
    console.log('Old ₹1 Pujas cleared.');

    console.log('Inserting 20 high-fidelity ₹1 Pujas...');
    const { data, error: insertErr } = await supabase
      .from('one_rupee_poojas')
      .insert(poojas);

    if (insertErr) throw insertErr;
    console.log('Successfully seeded 20 ₹1 Pujas! Count inserted:', poojas.length);
    process.exit(0);
  } catch (err) {
    console.error('Error seeding data:', err);
    process.exit(1);
  }
}

seed();
