const { createClient } = require('@supabase/supabase-js');
const dns = require('dns');
dns.setDefaultResultOrder('ipv4first');

const supabaseUrl = 'https://vjkwmefdutltwccpgnny.supabase.co';
const supabaseKey = 'sb_publishable_gZzOlAfCHCDDgdTbMop8zQ_18bQRX0L';

const supabase = createClient(supabaseUrl, supabaseKey);

const poojas = [
  {
    title: 'Ganesh Vignaharta Puja',
    original_price: '₹1,501',
    offer_price: '₹501',
    rating: '4.9',
    reviews: '340',
    provider: 'Siddhivinayak Temple Priests',
    image_url: 'https://images.unsplash.com/photo-1567591974574-e8b28634e35f?auto=format&fit=crop&w=600&q=80',
    tag: 'Success',
    requirement: 'Book Puja to claim',
    category: 'Auspicious',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Remove obstacles and invoke prosperity in your career and home.',
    benefits: '• Dissolves obstacles in career, business, and personal ventures\n• Attracts positive energy and intelligence into your workspace\n• Brings Ganesha\'s direct blessings of wisdom and auspiciousness',
    steps: '• Ganesha Avahanam & Sankalp chanting with name & gotra\n• Ganesh Atharvashirsha path recitation by holy pandits\n• Modak offering & final Mangal aarti',
    samagri: 'Durva grass, fresh modaks, red hibiscus flowers, red vermilion, and pure ghee.',
    pandit: 'Acharya Vinayak Shastri',
    temple: 'Prabhadevi Siddhivinayak Mandir, Mumbai',
    prasad: 'Vacuum-sealed box containing holy Modak sweets, consecrated red thread, and Siddhivinayak pocket picture card.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹501',
    single_original_price: '₹1,501',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,000',
    family_original_price: '₹3,000',
    sort_order_home: 1,
    sort_order_puja: 1,
    sort_order_store: 1
  },
  {
    title: 'Maha Laxmi Wealth Puja',
    original_price: '₹3,100',
    offer_price: '₹1,100',
    rating: '4.9',
    reviews: '520',
    provider: 'Mahalakshmi Priests',
    image_url: 'https://images.unsplash.com/photo-1609137144814-6c3614275f7e?auto=format&fit=crop&w=600&q=80',
    tag: 'Wealth',
    requirement: 'Book Puja to claim',
    category: 'Wealth',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Attract financial abundance, luxury, and success in trade.',
    benefits: '• Activates continuous inflows of wealth and business growth\n• Cleanses negative financial blocks and helps in debt clearance\n• Welcomes lasting household abundance and family prosperity',
    steps: '• Laxmi Aavahan Puja & name-specific Sankalp\n• Ashta-Laxmi Stotram Recitation by head priests\n• Sacred Havan offering with lotus seeds',
    samagri: 'Lotus seed mala, saffron threads, red rose petals, and cow ghee.',
    pandit: 'Pandit Ramesh Chaturvedi',
    temple: 'Mahalakshmi Temple, Kolhapur',
    prasad: 'Consecrated copper Shree Yantra shield, dry fruit panchamrit, and sacred thread.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,100',
    single_original_price: '₹3,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹2,200',
    family_original_price: '₹6,200',
    sort_order_home: 2,
    sort_order_puja: 2,
    sort_order_store: 2
  },
  {
    title: 'Shiv Kripa Rudrabhishek Havan',
    original_price: '₹2,100',
    offer_price: '₹751',
    rating: '4.9',
    reviews: '610',
    provider: 'Kashi Vedic Pandits',
    image_url: 'https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?auto=format&fit=crop&w=600&q=80',
    tag: 'Blessings',
    requirement: 'Book Puja to claim',
    category: 'Mahadev',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Purify sins, secure health, and invoke Lord Shivas divine protection.',
    benefits: '• Nullifies negative karmic patterns and ancestral debts\n• Grants extreme peace of mind and mental balance\n• Bestows longevity, health, and spiritual awakening',
    steps: '• Mahadev Avahanam & milk/honey abhishek\n• Chanting of 108 Shiv Shasranama verses with your name sankalp\n• Bilvapatra offerings & final Kashi Ganga aarti',
    samagri: 'Sacred Gangajal, organic milk, honey, fresh bilvapatra leaves, and white chandan.',
    pandit: 'Acharya Raman Shastri',
    temple: 'Kashi Vishwanath Shrine, Varanasi',
    prasad: 'Holy Gangajal bottle, energized Shiva pocket card, and dry sweet peda prasad.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹751',
    single_original_price: '₹2,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,500',
    family_original_price: '₹4,200',
    sort_order_home: 3,
    sort_order_puja: 3,
    sort_order_store: 3
  },
  {
    title: 'Sankat Mochan Hanuman Path',
    original_price: '₹999',
    offer_price: '₹351',
    rating: '4.8',
    reviews: '410',
    provider: 'Ayodhya Garhi Priests',
    image_url: 'https://images.unsplash.com/photo-1615818499660-30bb587f48d9?auto=format&fit=crop&w=600&q=80',
    tag: 'Protection',
    requirement: 'Book Puja to claim',
    category: 'Protection',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Ward off negative energies, planetary doshas, and secure robust health.',
    benefits: '• Shields your family from evil forces, planetary doshas, and enemies\n• Enhances physical stamina, courage, and mental clarity\n• Restores peace and harmony in turbulent households',
    steps: '• Lord Hanuman Avahanam & personal gotra Sankalp\n• Complete Hanuman Chalisa and Bajrang Baan recitations\n• Sindoor shringar and oil lamp offering',
    samagri: 'Sacred vermilion (sindoor), mustard oil, dynamic tulsi leaf mala, and gram laddoos.',
    pandit: 'Acharya Bajrang Shastri',
    temple: 'Hanuman Garhi Temple, Ayodhya',
    prasad: 'Energized Hanuman pocket kavach card, Garhi sacred orange paste, and holy tulsi seeds.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹351',
    single_original_price: '₹999',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹700',
    family_original_price: '₹1,998',
    sort_order_home: 4,
    sort_order_puja: 4,
    sort_order_store: 4
  },
  {
    title: 'Basar Saraswati Vidya Puja',
    original_price: '₹1,501',
    offer_price: '₹501',
    rating: '4.8',
    reviews: '190',
    provider: 'Basar Temple Scholars',
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    tag: 'Education',
    requirement: 'Book Puja to claim',
    category: 'Auspicious',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Boost concentration, intellect, and academic success for children.',
    benefits: '• Improves memory power, logical skills, and educational performance\n• Enhances artistic talents, musical flow, and communication skills\n• Establishes focus and blocks exams-related anxiety',
    steps: '• Saraswati Devi Avahanam & book/pen dedication\n• Chanting of Saraswati Beej mantras with name sankalp\n• White flower tribute & final lamp aarti',
    samagri: 'White marigold flowers, chandan paste, yellow rice, and cardamom sweets.',
    pandit: 'Pandit Sharad Dwivedi',
    temple: 'Basar Gnana Saraswathi Mandir',
    prasad: 'Energized copper Saraswati Yantra card, sacred yellow thread, and sweet sugar candies.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹501',
    single_original_price: '₹1,501',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,000',
    family_original_price: '₹3,002',
    sort_order_home: 5,
    sort_order_puja: 5,
    sort_order_store: 5
  },
  {
    title: 'Shani Dev Grah Shanti',
    original_price: '₹2,500',
    offer_price: '₹851',
    rating: '4.7',
    reviews: '480',
    provider: 'Shingnapur Shani Acharyas',
    image_url: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=600&q=80',
    tag: 'Astro',
    requirement: 'Book Puja to claim',
    category: 'Protection',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Calm the malefic effects of Saturn Sade Sati and Dhaiya.',
    benefits: '• Decreases obstacles, financial constraints, and delays caused by Saturn\n• Restores mental calm and protects from accidents/sudden falls\n• Enhances discipline, hard work reward, and business stability',
    steps: '• Shani Dev Avahanam & black sesame oil bath dedication\n• Recitation of Shani Stotram & Shani Mantra with name sankalp\n• Iron ring dedication & final protection aarti',
    samagri: 'Black sesame oil, black cloth, iron nails, blue flowers, and black gram.',
    pandit: 'Acharya Shani Dev Shastry',
    temple: 'Shani Shingnapur Mandir, Maharashtra',
    prasad: 'Energized iron Shani ring, sacred black thread, and temple chandan powder.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹851',
    single_original_price: '₹2,500',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,700',
    family_original_price: '₹5,000',
    sort_order_home: 6,
    sort_order_puja: 6,
    sort_order_store: 6
  },
  {
    title: 'Durga Shatru Nashini Puja',
    original_price: '₹3,100',
    offer_price: '₹1,100',
    rating: '4.9',
    reviews: '290',
    provider: 'Jwala Ji Shrine Acharyas',
    image_url: 'https://images.unsplash.com/photo-1561571994-3c61c554181a?auto=format&fit=crop&w=600&q=80',
    tag: 'Shield',
    requirement: 'Book Puja to claim',
    category: 'Protection',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Divine armor for victory over legal hurdles and enemies.',
    benefits: '• Grants supreme protective shield against black magic and jealousy\n• Helps achieve victory in court disputes and property battles\n• Fosters inner strength and eliminates deep-rooted fears',
    steps: '• Durga Devi Avahanam & weapon empowerment ritual\n• Chanting of Durga Saptashati Shlokas with your name/gotra\n• Red vermilion offering & final high-energy aarti',
    samagri: 'Red chunri, coconut, red vermilion, dry coconut kernel, and camphor.',
    pandit: 'Pandit Somnath Dwivedi',
    temple: 'Jwala Ji Durga Temple, Himachal Pradesh',
    prasad: 'Blessed red Durga chunri, energized copper Durga pocket card, and temple vermilion.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,100',
    single_original_price: '₹3,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹2,200',
    family_original_price: '₹6,200',
    sort_order_home: 7,
    sort_order_puja: 7,
    sort_order_store: 7
  },
  {
    title: 'Kanakadhara Lakshmi Yagya',
    original_price: '₹5,100',
    offer_price: '₹2,100',
    rating: '4.9',
    reviews: '310',
    provider: 'Sree Padmanabha Scholars',
    image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80',
    tag: 'Gold Flow',
    requirement: 'Book Puja to claim',
    category: 'Wealth',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Manifest gold and wealth opportunities with sacred hymns.',
    benefits: '• Invokes the golden shower of wealth and luck into your family\n• Clears business stagnation and opens multiple income streams\n• Bestows luxurious comforts, assets, and vehicle purchases',
    steps: '• Lakshmi Avahanam & gold-plated coins shringar\n• Chanting of Kanakadhara Stotram 18 times with name sankalp\n• Lotus flower dedication & dynamic final aarti',
    samagri: 'Gold-plated coins, fresh lotus flowers, pure honey, and aromatic incense.',
    pandit: 'Acharya Padmanabhan',
    temple: 'Sree Padmanabhaswamy Temple, Kerala',
    prasad: 'Energized Kanakadhara card, sacred yellow thread, and dry sugar candy prasad.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹2,100',
    single_original_price: '₹5,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹4,200',
    family_original_price: '₹10,200',
    sort_order_home: 8,
    sort_order_puja: 8,
    sort_order_store: 8
  },
  {
    title: 'Mahamrityunjaya Healing Puja',
    original_price: '₹4,500',
    offer_price: '₹1,500',
    rating: '4.9',
    reviews: '670',
    provider: 'Ujjain Mahakal Acharyas',
    image_url: 'https://images.unsplash.com/photo-1616038242814-a6eac7845d88?auto=format&fit=crop&w=600&q=80',
    tag: 'Health',
    requirement: 'Book Puja to claim',
    category: 'Peace',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Recover from severe diseases, bad energy, and restore vitality.',
    benefits: '• Neutralizes severe health threats and heals old illness blocks\n• Eradicates negative energy and mental depression triggers\n• Bestows robust health, high vitality, and a peaceful long life',
    steps: '• Mahakal Avahanam & personal health gotra Sankalp\n• Chanting of Mahamrityunjaya Mantra 108 times by Vedic priests\n• Bhasma shringar tribute & final Ujjain Aarti',
    samagri: 'Sacred bhasma (holy ash), bilva leaves, sesame seeds, and white flowers.',
    pandit: 'Acharya Somesh Shastri',
    temple: 'Mahakaleshwar Jyotirlinga Mandir, Ujjain',
    prasad: 'Blessed Mahakal Bhasma packet, energized rudraksha bead, and sacred red thread.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,500',
    single_original_price: '₹4,500',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹3,000',
    family_original_price: '₹9,000',
    sort_order_home: 9,
    sort_order_puja: 9,
    sort_order_store: 9
  },
  {
    title: 'Navgrah Dosha Shanti',
    original_price: '₹3,500',
    offer_price: '₹1,250',
    rating: '4.8',
    reviews: '550',
    provider: 'Navagraha Dham Pandits',
    image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    tag: 'Astro',
    requirement: 'Book Puja to claim',
    category: 'Protection',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Harmonize Rahu, Ketu, Saturn and balance all 9 planets in your chart.',
    benefits: '• Decreases malefic planetary dashas (Rahu, Ketu, Saturn, etc.)\n• Harmonizes relationships, career flow, and financial blocks\n• Minimizes unexpected troubles and builds positive planetary luck',
    steps: '• Navagraha Avahanam & colorful grains layout\n• Chanting of Navagraha Stotram & separate planet mantras with name sankalp\n• Nine-color flower dedication & final light rotation',
    samagri: 'Nine-color cloth blocks, nine different grains, pure camphor, and ghee lamps.',
    pandit: 'Acharya Devrath Joshi',
    temple: 'Navagraha Temple, Guwahati, Assam',
    prasad: 'Energized Navagraha copper kavach sheet, sacred colored thread, and chandan paste.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,250',
    single_original_price: '₹3,500',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹2,500',
    family_original_price: '₹7,000',
    sort_order_home: 10,
    sort_order_puja: 10,
    sort_order_store: 10
  },
  {
    title: 'Surya Dev Career Homa',
    original_price: '₹1,501',
    offer_price: '₹501',
    rating: '4.8',
    reviews: '230',
    provider: 'Konark Aditya Acharyas',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    tag: 'Glory',
    requirement: 'Book Puja to claim',
    category: 'Auspicious',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Gain leadership command, respect, and career glory.',
    benefits: '• Bestows leadership authority, respect, and high recognition\n• Helps secure government jobs and win political support\n• Heals eye issues, bone weakness, and physical laziness',
    steps: '• Lord Surya Avahanam & copper vessel water offering\n• Chanting of Aditya Hrudaya Stotram with name sankalp\n• Red chandan and wheat offerings & final sun aarti',
    samagri: 'Red sandal paste, wheat grains, copper plates, and red flowers.',
    pandit: 'Pandit Bhaskar Shastri',
    temple: 'Konark Sun Temple Circle, Odisha',
    prasad: 'Energized Surya copper coin card, red chandan powder, and wheat seeds.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹501',
    single_original_price: '₹1,501',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,000',
    family_original_price: '₹3,000',
    sort_order_home: 11,
    sort_order_puja: 11,
    sort_order_store: 11
  },
  {
    title: 'Radha Krishna Prem Seva',
    original_price: '₹2,100',
    offer_price: '₹751',
    rating: '4.9',
    reviews: '430',
    provider: 'Vrindavan Dham Goswamis',
    image_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=600&q=80',
    tag: 'Love',
    requirement: 'Book Puja to claim',
    category: 'Peace',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Resolve relationship differences and establish home harmony.',
    benefits: '• Restores deep love, understanding, and trust in relationships\n• Resolves marriage delays and matches you with a good partner\n• Fills your home with peaceful devotional vibrations and joy',
    steps: '• Radha Krishna Shringar & fresh flower decoration\n• Chreading of Madhurashtakam & Prem mantras with name/gotra sankalp\n• Tulsi leaf dedication & Vrindavan sweet modak offering',
    samagri: 'Fresh rose petals, dynamic tulsi leaves, vrindavan pedas, and aromatic perfume.',
    pandit: 'Pandit Banke Lal Goswami',
    temple: 'Banke Bihari Temple, Vrindavan',
    prasad: 'Blessed Radha-Krishna pocket card, vrindavan chandan powder, and tulsi leaves.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹751',
    single_original_price: '₹2,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,500',
    family_original_price: '₹4,200',
    sort_order_home: 12,
    sort_order_puja: 12,
    sort_order_store: 12
  },
  {
    title: 'Kaal Bhairav Protection Homa',
    original_price: '₹3,100',
    offer_price: '₹1,150',
    rating: '4.9',
    reviews: '380',
    provider: 'Kashi Bhairav Priests',
    image_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=600&q=80',
    tag: 'Protection',
    requirement: 'Book Puja to claim',
    category: 'Protection',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Eliminate toxic threats, lawsuits, and bad luck dashas.',
    benefits: '• Eradicates toxic people, court lawsuits, and bad luck influences\n• Acts as a severe shield against sudden planetary accidents\n• Bestows absolute fearlessness and restores self-confidence',
    steps: '• Lord Kala Bhairav Avahanam & black thread offering\n• Chanting of Bhairav Ashtakam with name/gotra sankalp\n• Mustard oil lamp illumination & dynamic final aarti',
    samagri: 'Mustard oil, black thread, coconut, standard liquor essence, and black raisins.',
    pandit: 'Acharya Kala Bhairav Shastri',
    temple: 'Kaal Bhairav Temple, Ujjain',
    prasad: 'Energized black Bhairav thread, sacred ash (bhasma), and oil lamp wick.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,150',
    single_original_price: '₹3,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹2,300',
    family_original_price: '₹6,200',
    sort_order_home: 13,
    sort_order_puja: 13,
    sort_order_store: 13
  },
  {
    title: 'Annapurna Food & Grace Puja',
    original_price: '₹1,501',
    offer_price: '₹501',
    rating: '4.9',
    reviews: '280',
    provider: 'Annapurna Temple Associates',
    image_url: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?auto=format&fit=crop&w=600&q=80',
    tag: 'Prosperity',
    requirement: 'Book Puja to claim',
    category: 'Peace',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Guarantee food abundance, health, and domestic harmony.',
    benefits: '• Ensures your family kitchen is always blessed with food abundance\n• Promotes robust digestive health, longevity, and metabolic flow\n• Eradicates domestic discords and welcomes absolute happiness',
    steps: '• Goddess Annapurna Avahanam & dynamic grain dedication\n• Annapurna Stotram chanting & name/gotra sankalp\n• Pure cow ghee sweets offering & final Mangal aarti',
    samagri: 'Wheat, rice grains, green gram, pure ghee sweets, and yellow flowers.',
    pandit: 'Acharya Somnath Goswami',
    temple: 'Annapurna Shrine, Varanasi, Uttar Pradesh',
    prasad: 'Energized Annapurna pocket card, sacred yellow thread, and blessed rice grains.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹501',
    single_original_price: '₹1,501',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹1,000',
    family_original_price: '₹3,000',
    sort_order_home: 14,
    sort_order_puja: 14,
    sort_order_store: 14
  },
  {
    title: 'Vishnu Sahasranama Archana',
    original_price: '₹3,100',
    offer_price: '₹1,100',
    rating: '4.9',
    reviews: '390',
    provider: 'Srirangam Ranganatha Scholars',
    image_url: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=600&q=80',
    tag: 'Blessings',
    requirement: 'Book Puja to claim',
    category: 'Auspicious',
    is_active_on_home: true,
    is_active: true,
    status: 'published',
    tagline: 'Fulfill wishes, balance stars, and gain wealth with Vishnu names.',
    benefits: '• Balances all astrological planetary doshas and cures blockages\n• Grants extreme family prosperity, name, and spiritual success\n• Invokes the protective shields of Lord Narayana over your health',
    steps: '• Lord Vishnu Avahanam & Tulsi leaf garland shringar\n• Recitation of complete 1,000 names of Lord Vishnu with your gotra sankalp\n• Dry fruit prasad offerings & final lamp standard aarti',
    samagri: 'Fresh tulsi leaf garland, yellow sandal paste, dry fruits, and aromatic incense.',
    pandit: 'Acharya Ranganatha Bhattar',
    temple: 'Sri Ranganathaswamy Temple, Srirangam',
    prasad: 'Blessed Tulsi leaves, energized Vishnu copper card, and sacred yellow thread.',
    other_info: 'Video proof of Sankalp shared on WhatsApp within 24 hours.',
    single_title: 'Single Sankalp',
    single_description: 'Individual name & gotra Sankalp + Holy Prasad transit box.',
    single_price: '₹1,100',
    single_original_price: '₹3,100',
    family_title: 'Family Pariwar',
    family_description: 'Full household (4 names) Sankalps + Consecrated copper yantra shield.',
    family_price: '₹2,200',
    family_original_price: '₹6,200',
    sort_order_home: 15,
    sort_order_puja: 15,
    sort_order_store: 15
  }
];

async function seed() {
  console.log('Clearing old General Pujas...');
  try {
    const { error: clearErr } = await supabase
      .from('general_poojas')
      .delete()
      .neq('id', '00000000-0000-0000-0000-000000000000'); // Delete all

    if (clearErr) throw clearErr;
    console.log('Old General Pujas cleared.');

    console.log('Inserting 15 high-fidelity General Pujas...');
    const { data, error: insertErr } = await supabase
      .from('general_poojas')
      .insert(poojas);

    if (insertErr) throw insertErr;
    console.log('Successfully seeded 15 General Pujas! Count inserted:', poojas.length);
    process.exit(0);
  } catch (err) {
    console.error('Error seeding data:', err);
    process.exit(1);
  }
}

seed();
